### ISSUE TITLE
Service does not start

### ISSUE THREAD

**Issue by muhrix** [clearpathrobotics/robot_upstart#9]
Hello,

I am trying to use `robot_upstart` with our Husky and I cannot get it to start the service, not even by running `sudo service husky-core start`. In this case, it does return a pid, but  it does not load anything at all (it appears to die straight away).

The command I used to install is:
`rosrun robot_upstart install my_package/launch/my_launch.launch --job husky-core --interface wlan0`

The nodes loaded from within the launch file are from packages installed system-wide (that is, not in my workspace).

This works on another computer, both running 12.04 + Hydro. Having said that, even on the other computer, I can load system-wide nodes, but I cannot load nodes from within my workspace.

Lastly, when I run `roslaunch my_package my_launch.launch`, everything works as expected (i.e., all nodes are loaded).

I have tried specifying options for `user` and the path to `setup.bash`, but no luck.
Oh, just in case, yes, the wlan0 interface is up at boot time.

Any ideas/suggestions?
Thanks a lot!

**Comment by mikepurvis** [comment]
Hi there!

The best first step in debugging this type of issue is to execute the job's start script manually, which will launch it in the foreground, giving you immediate access to any issues you may have with your nodes, launchfiles, packages, permissions, etc. Please try the following, and report any errors it encounters:

```
sudo husky-core-start
```

You can also inspect the contents of `/etc/init/husky-core.conf` and `/usr/sbin/husky-core-start` to ensure that they match your expectations, especially about users, the correct workspace setup file being sourced, etc.

**Comment by muhrix** [comment]
Hello! thanks for replying so quickly! :-)

Naively, I did not realise I could run the service on the foreground; thanks for suggesting that!
It is an issue with permissions, more specifically, denied access to a serial port.

I thought that if I specified the user, then the groups this user belongs to would hold whilst executing the service.
Off the top of my head, I do not know how to solve this issue, but I'll try and figure out.

Thanks again!

**Comment by jeff-o** [comment]
A quick way to enable permissions is to use chmod.  For example, this command would allow full read/write access to serial port ttyS0:

sudo chmod 666 /dev/ttyS0

The long-term solution is to install a udev rule. Navigate to /etc/udev/rules.d and (sudo) create a new file called 40-permissions.rules.  Populate it with this line:

KERNEL=="ttyS0", MODE="0666"

Save and exit the file.  Then run this command to update your udev rules:

sudo service udev restart

All users should now have full access to ttyS0.

**Comment by muhrix** [comment]
Well, in theory, I should not need to use chmod, as I added the user to the dialout group.

I would rather not have to change/create new udev rules, or allow "others" read/write access to the serial port. I'll eventually do that if I can't find a different solution. :-)

Since this issue is no longer related to `robot_upstart`, I'm closing it.
I really appreciate your suggestions, thanks a lot.

**Comment by mikepurvis** [comment]
The issue is that the upstart job executes as root and uses setuidgid to run the roslaunch process as the appropriate unprivileged user:

https://github.com/clearpathrobotics/robot_upstart/blob/hydro-devel/tmpl/start#L80

Unfortunately, setuidgid does _not_ pick up the user's group memberships, so you need a udev rule to either make the device world RW or to specifically chown it to your ROS user (**administrator**, on Clearpath-configured robot PCs).

**Comment by muhrix** [comment]
I saw that setuidgid was being used, but I did not know it doesn't take the list of groups the user belongs to into account.

I'll have to change the udev rules, as suggested, then. That will do.
Thanks again! ;-)

**Comment by girtslinde** [comment]
I just had to spend some time troubleshooting the permissions on my robot as well. Sure enough, it was the problem with the dialout group. If udev is the solution, it deserves a sentence on the wiki page, so that people know they will hit this.

I found that setuidgid from http://untroubled.org/daemontools-encore/ has a parameter to set the supplementary gids as well, and that works for me. I wonder if it would be a good idea to include a patched setuidgid with the upstart package to take care of the permissions automatically.

**Comment by mikepurvis** [comment]
In the short term, I've added a permissions section to the wiki to explain a bit about what's going on here:

http://wiki.ros.org/robot_upstart#Permissions

**Comment by davidhodo** [comment]
The way I've solved this in the past is to use the setuid and setgid functionality in upstart (http://upstart.ubuntu.com/cookbook/#setgid).  Instead of launching using setuidgid, call roslaunch normally but add setuid and setgid lines to the /etc/init/[job].conf file.  Setuid should be set to the user to launch the nodes as and setgid should be set to dialout to allow serial port access.  I've been modifying the output of robot_upstart manually to do this but could modify the scripts to allow a separate group to be specified if that would be useful to others.
